times = ('Corinthians', 'Atletico - MG', 'Bragantino', 'Flamengo', 'Santos', 'Fluminense', 'São Paulo', 'Coritiba', 'América - MG', 'Botafogo', 'Cuiabá', 'Ceará', 'Internacional', 'Avaí', 'Palmeiras', 'Juventude', 'Goiás', 'Atlético - GO', 'Fortaleza', 'Athletico - PR')
print(f'Tabela do Brasileirão: {times}')
print('--'*25)
print(f'Os 5 primeiros colocados são: {times[:5]}')
print('--'*25)
print(f'Os últimos 4 colocados são: {times[16:]}')
print('--'*25)
print(f'Os times em ordem alfabética: {sorted(times)}')
print('--'*25)
print(f'O Palmeiras está na {times.index("Palmeiras") + 1}ª posição.')
